# Generated by Django 4.0.7 on 2023-03-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusRouteDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BusRoute', models.CharField(max_length=10)),
                ('From', models.CharField(max_length=50)),
                ('To', models.CharField(max_length=50)),
                ('TicketAmount', models.IntegerField()),
                ('Duration_in_Minutes', models.IntegerField()),
            ],
        ),
    ]
